name: deploy appsmith
on:
  workflow_dispatch:
jobs:
  deploy:
    runs-on: [my-machine]
    steps:
      - name: checkout
        uses: actions/checkout@v4
     
      - name: run docker command
        run: docker compose up -d
      
      - name: access appsmith
        run: docker ps
        
